from core.views.redirect_home_view import redirect_home_view
from core.views.privacy_policy_view import PrivacyPolicyView, TermsAndConditionsView
from core.views.page_not_found_view import PageNotFoundView
from core.views.server_error_view import server_error
