from core.views.redirect_home_view import redirect_home_view
from core.views.privacy_policy_view import PrivacyPolicyView, TermsAndConditionsView
from core.views.landing_page_view import LandingPageView
