# Generated by Django 3.0.6 on 2020-06-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la promoción')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código de la promoción')),
                ('cart_discount', models.TextField(choices=[('PERC', 'Porcentaje'), ('FIXED', 'Cantidad fija'), ('FREE', 'Gratis')], default='PERC', max_length=6, verbose_name='Tipo de descuento')),
                ('discount_mount', models.IntegerField(default=0, verbose_name='Porcentaje o cantidad de descuento')),
                ('expiry_datetime', models.DateTimeField(verbose_name='Fecha y hora de vencimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Promoción válida')),
            ],
            options={
                'verbose_name': 'Código promocional',
                'verbose_name_plural': 'Códigos promocionales',
            },
        ),
    ]
