# Generated by Django 3.0.6 on 2020-05-26 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('status', models.IntegerField(choices=[(1, 'Solicitado'), (2, 'En camino'), (3, 'Entregado / Pagado'), (4, 'Cancelado')], default=1, verbose_name='Estatus del pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre y apellido')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Código postal')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('city', models.CharField(max_length=255, verbose_name='Delegación / Municipio')),
                ('colony', models.CharField(max_length=255, verbose_name='Barrio / Colonia / Asentamiento')),
                ('street_name', models.CharField(max_length=255, verbose_name='Calle')),
                ('street_number', models.CharField(max_length=10, verbose_name='N° Exterior')),
                ('internal_number', models.CharField(blank=True, max_length=10, verbose_name='N° Interior / Depto (opcional)')),
                ('between_street1', models.CharField(blank=True, max_length=255, verbose_name='Calle 1')),
                ('between_street2', models.CharField(blank=True, max_length=255, verbose_name='Calle 2')),
                ('telephone', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('references', models.TextField(max_length=500, verbose_name='Ayuda al repartido a encontrar tu domicilio o el producto que necesitas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Número de productos pedidos')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductPrice')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.OrderAddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.OrderProduct', to='products.ProductPrice'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='orderproduct',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_by_order'),
        ),
    ]
