# Generated by Django 3.0.6 on 2020-09-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200616_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solicitado'), (2, 'En camino'), (3, 'Entregado / Pagado'), (4, 'Cancelado'), (5, 'Cocinándose')], default=1, verbose_name='Estatus del pedido'),
        ),
    ]
