# Generated by Django 3.0.6 on 2020-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Palabras clave de búsqueda'),
        ),
        migrations.AddField(
            model_name='provider',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Palabras clave de búsqueda'),
        ),
    ]
