# Generated by Django 3.0.6 on 2020-06-10 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200601_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('name', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0, verbose_name='Día de la semana')),
                ('start_time', models.TimeField(null=True, verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(null=True, verbose_name='Hora final')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
