# Generated by Django 3.0.6 on 2020-07-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['order'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='product',
            name='price_default',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='El precio por default que muestra en el inicio'),
        ),
        migrations.AddField(
            model_name='provider',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Orden en el que deberían aparecer los proveedores'),
        ),
    ]
